/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterCustomersRouteImport } from './routes/master/customers'
import { Route as MasterAddCustomerRouteImport } from './routes/master/add-customer'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCustomersRoute = MasterCustomersRouteImport.update({
  id: '/master/customers',
  path: '/master/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAddCustomerRoute = MasterAddCustomerRouteImport.update({
  id: '/master/add-customer',
  path: '/master/add-customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master/add-customer': typeof MasterAddCustomerRoute
  '/master/customers': typeof MasterCustomersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master/add-customer': typeof MasterAddCustomerRoute
  '/master/customers': typeof MasterCustomersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master/add-customer': typeof MasterAddCustomerRoute
  '/master/customers': typeof MasterCustomersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/master/add-customer' | '/master/customers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/master/add-customer' | '/master/customers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/master/add-customer'
    | '/master/customers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MasterAddCustomerRoute: typeof MasterAddCustomerRoute
  MasterCustomersRoute: typeof MasterCustomersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customers': {
      id: '/master/customers'
      path: '/master/customers'
      fullPath: '/master/customers'
      preLoaderRoute: typeof MasterCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/add-customer': {
      id: '/master/add-customer'
      path: '/master/add-customer'
      fullPath: '/master/add-customer'
      preLoaderRoute: typeof MasterAddCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MasterAddCustomerRoute: MasterAddCustomerRoute,
  MasterCustomersRoute: MasterCustomersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
